db:
  mongodb:
    url: 'tradingbot.lorm4.mongodb.net'
    database: 'tradingbot'
    user: 'admin'
    password: 'p7nZUdHzkfYAJ2Z'
    params:
      retryWrites: true
      w: 'majority'
storage:
  bucket:
    # TODO: Should be changed to coinlister-bucket
    name: 'coinlister_proxies_bucket'

